
export const userDetailFormConstants = {
    emailIsRequired: 'E-Mail is Required',
    emailValidationMessage: "Please enter a valid email!",
    postalCodeValidationMessage: 'Please enter valid Postal Code',
    phoneNumberNumeric: 'Phone No must be Numeric',
    mobileNumberNumeric: 'Mobile No must be Numeric',
    faxNumberNumeric: 'Fax No must be Numeric',
}

export const quoteConstants = {
    topstripeLabel:'Create, View and Send Quotes',
    myQuoteLabel: 'NEW CUSTOMER QUOTE',
    quotesLabel: 'CUSTOMER QUOTES',
    createNewLabel:'Create New',
    viewQuoteLabel:'View quote',
    newQuoteLabel:'New Quote',
    editQuoteLabel:'Edit Quote',
    jobDetailsText:'Job Details',
    jobDetailsUpdateText:'Update Job Details',
    jobAddressLabel:'Job Location',
    notesLabel:'Notes',
    jobReferenceLabel:'Job Reference',
    jobLocationLabel:'Job Location',
    customerDetailsText:'CLIENT DETAILS',
    customerNameLabel:'Client Name',
    mobileLabel:'Phone',
    emailLabel:'Email Address',
    customerAddressLabel:'Client Address',
    errorMsgJobreference:'Please enter name or number',
    errorMsgAddress:'Please enter a valid address',
    errorMsgMobile:'Please enter a valid mobile number',
    errorMsgPhone:'Please enter a valid number',
    errorMsgEmail:'Please enter a valid email address',
    cancelQuoteLabel:'Cancel Quote Details',
    cancelInfoMsg:'Any details you may have entered will not be saved. Are you sure you want to cancel?',
    cancelText:'Cancel',
    ConfirmText:'Confirm',
    TotalPriceLabel: 'Total excl. GST',
    sku: 'SKU: ',
    itemCode: 'Item Code:',
    retailPriceLabel: 'RRP ',
    totalLength: 'TOTAL LENGTH ',
    addToQuoteBtn: 'Add to Quote',
    addedBtn: 'Added',
    searchPlaceholder: 'Search for TradeLink products to add to your quote',
    loadMoreBtn: 'Load More',
    loadMoreMessagePart1: "You've viewed ",
    loadMoreMessagePart2: ' products',
    createQuote:'Create Quote',
    AddProductQuote:'Add Materials & Products',
    AddNewProducts: 'Add Products',
    updateBtn:"Update",
    noResultsFound:"No results found",
    noImage:'assets/images/quoteimagenotfound.svg',
    noResultsMessage: 'Sorry we couldn’t find any results for your search. Please try again.',
    costTotal:'Costs total (total of all costs added)',
    editMarkup: 'Mark-up',
    addMarkup: 'Mark-up',
    allProductAdded: 'Add Your Own Products',
    repriceLabel: 'Update',
    withLatestPriceLabel: 'with Latest Prices',
    repriceSuccessMessage: 'Your latest Mico pricing is now showing',
    repriceWarningMessage: 'Unable to get latest pricing. Please try again later.',
    productDeleteMessage: 'Product deleted',
    costDeleteMessage: 'Cost deleted',
    priceApiDownError: 'Unable to get pricing. Please try again later.',   
    reviewQuote: 'Review Quote',             
    viewQuote: 'View Quote' ,            
    scopeofworkText:'SCOPE OF WORK',
    scopeofworkTextLimit:'10,000 characters',
    reviewTotalPrice: 'Total Customer Price Incl. GST',
    goBackBtn: 'Go Back',
    sendToCustomerBtn: 'Send to Customer',
    addressPlaceholder: 'Enter address',
    setUp:'Let’s get set up',
    companySettings:'Company settings',
    quoteDeletedMessage: 'has been deleted.',
    deleteQuoteLink: 'Delete quote',
    startQuotes:'Create a new quote',
    emptyStateTitle:'Create a simple quote',
    emptyStateInfo:'We notice it’s your first time here. Before you start you can add your business details, payment information and your company logo',
    emptyStateInfoCompany:'We notice you’ve added your business details but you can change these when you are reviewing your quotes.  It’s now time to create your first quote',
    quoteStatusInProgressLbl: 'In progress',
    quoteStatusPendingLbl: 'Pending',
    quoteStatusWonLbl: 'Accepted',
    quoteStatusLostLbl: 'Declined',
    quoteStatusBtnText: 'Mark quote as:',
    wonTitle: 'Congratulations, you have won',
    lostTitle: 'Sorry to hear you were not successful on', 
    wonDescription : [
                        'This quote will now move to “won” section in quotes so you can review it at any time (no updates available)',  
                        'We will also send the details to Mico', 
                        'so they can load this into your “Jobs” section so you can simply order from it at any time. Please allow us some time to enter this for you',
                        'Do you wish to confirm the job is won?'                        
                     ],
    lostDescription: [
                        'This quote will now move to “lost” section in quotes so you can review it at any time (no updates available)', 
                        'Do you wish to confirm the job has been lost?'
                     ],
    emptyInprogressStatusTabHeading: 'In Progress Quotes',
    emptyPendingStatusTabHeading: 'Pending Quotes',
    emptyWonStatusTabHeading: 'Won Quotes',
    emptyLostStatusTabHeading: 'Lost Quotes',
    emptyInprogressStatusTab: 'Here you can see the quotes that you have created but not yet sent to your clients. It’s now time to create a new quote.',
    emptyPendingStatusTab: 'Here you can see the quotes you have sent to your customers. Once they have let you know you have won the job simply select won and a new job account will be created so you can start ordering right away.',
    emptyWonStatusTab: 'Here you can see the quotes you have won. Look back here to review all your previous work.',
    emptyLostStatusTab: 'Here you can see any quotes you unfortunately did not win. Look back here to review all your previous work, or edit and re-submit if you get a further opportunity.',
    editQuote:'Edit quote?',
    editQuoteInfo:'You are about to edit this quote. Making changes will set the quote status to ‘In Progress’. You will need to resend the quote to your customer. Do you want to continue?',
    companySetupTC: 'Estimate only. Valid for 30 days from date of issue. Freight and Supplier price increases will not be included.'
}

export const headerLabels = {
    selectJobAccText: 'Select Job Account'
}

export const jobDetailConstants = {
    jobDetails: 'Job Details',
    materials: 'Add Materials & Products',
    materialReview: 'Materials & Products',
    labourOtherCosts: 'Labour / Other Costs',
    dateCreated: 'Created on:',
    createdDate: 'Date created:',
    jobAddress: 'Job Location',
    notes: 'Notes:',
    customerDetail: 'Client Details',
    customerDetailReview: 'CLIENT DETAILS',
    names: 'Name:',
    phone: 'Phone:',
    email: 'Email:',
    address: 'Address:',
    AddOwnProduct:'Add Your Own Products',
    ProductsAdded:'Products added',
    searchPlaceholder:'Search for TradeLink products to add to your quote',
    costSummary: 'Cost Summary',
    material: 'Materials',
    markup: 'Mark-up',
    subTotal: 'Subtotal',
    scopeOfWork: 'Scope of Work',
    reviewScopeOfWork: 'SCOPE OF WORK',
    customerPrice: 'CLIENT\'S PRICE',
    materialIncMarkup: 'Materials (Incl. Mark-up):',
    rrp: 'RRP',
    labourOtherCost: 'Labour / Other Costs:',
    gst: 'GST',
    totalCustPriceSmall: 'Total Client Price :',
    totalCustPrice: 'Total Client Price',
    markUpPrice: "Material's Mark-up",
    scopeofworkText:'Scope of Work',
    totalPriceText:'Total',
    excludeGSTText:'(excl. GST)',
    productHeading: 'Materials & Products',
    previewButton: 'Preview'
}

export const addProduct = {
    addYourOwnProduct: 'Add Your Own Products',
    productName: 'Product Name',
    price: 'Price',
    descriptionOrNotes: 'Description / Notes',
    unitOfMeasure: 'Unit of Measure',
    quantity: 'Quantity',
    addToQuote: 'Add to Quote',
    cancel: 'Cancel',
    priceError: 'Please enter price',
    nameError: 'Please enter product name',
    cancelTitle: 'Cancel your own product'
}

export const addEditProduct = {
    addMaterialMarkup: 'Add Materials & Products Mark-up',
    editMaterialMarkup: 'Edit Materials Mark-up',
    markUp: 'Mark-up',
    materialCost: 'Material Cost:',
    markUpPrice: 'Mark-up Price:',
    materialTotal: 'Materials Total:',
    add: 'Add to Quote',
    update: 'Update to Quote',
    cancelTitle: 'Cancel mark up'
}

export const labourCost = {
    costs:'Costs',
    cost:'Costs',
    add:'Add',
    edit:'Edit',
    labourCostsLabel:'Labour Costs',
    subContractorCostsLabel:'Sub Contractor Costs',
    overheadsLabel:'Overheads',
    otherCostsLabel:'Other Costs',
    labourCostLabel:'Add Labour Cost',
    subContractorCostLabel:'Add Sub Contractor Cost',
    overheadsCostLabel:'Add Overheads Cost',
    otherCostLabel:'Add Other Cost',
    noCostsAdded:'No costs added',
    costsAdded:'Costs added',
    hours:'Hours',
    hoursOther: 'Cost Price',
    chargeRate:'Hourly Rate',
    chargeRateOther:'Charge rate',
    note:'Note',
    chargeRatePlaceholderLabour:'Enter Hourly rate',
    chargeRatePlaceholderOther:'Enter Hourly rate',
    chargeRatePlaceholderOverhead:'Enter the cost for the overhead',
    chargeRatePlaceholderSubContractor:'Enter the charge rate for this subcontractor',
    namePlaceholderLabour:'Enter name e.g. Plumber, Drainlayer, Gasfitter etc.',
    namePlaceholderOther:'Enter type of cost e.g. Site services',
    namePlaceholderOverhead:'Enter name of costs eg, Rent, Admin costs, Utilities, Insurance',
    namePlaceholderSubContractor:'Enter name or type of sub contractor eg Plumber, Sparky etc',
    labourCostTip:'Tip: Add 30% to your labour cost or use the Overhead section to cover your day to day running costs.',
    overheadsCostTip:'Tip: Add overhead costs to cover your day to day running costs.',
    otherCostTip:'Tip: Add any other costs that are needed to complete this job.',
    subContractorCostTip:'Tip: Add any sub contracting costs that are needed to complete this job.',
    costQtyFieldPlaceholder:'Enter the number of hours expected to complete the job eg 7.5',
    labourCostsEmptyStateMessage1: 'Add labour costs for you and your team',
    labourCostsEmptyStateMessage2: 'Remember to add costs to cover holidays and sickness',
    subContractorCostsEmptyStateMessage1: 'Add Sub Contractor costs',
    subContractorCostsEmptyStateMessage2: 'Add any Sub Contractor costs required for you to complete the job',
    overheadsEmptyStateMessage1: 'Add Overhead costs',
    overheadsEmptyStateMessage2: 'Add Overheads to the quote to cover the day to day running of your business',
    otherCostsEmptyStateMessage1: 'Add Other costs',
    otherCostsEmptyStateMessage2: 'Add any other costs you might incur whilst completing this job',
    cancelQuoteLabel:'Cancel adding cost?',
    errorMsgName:'Please Enter Cost name',
    errorCostPrice: 'Please Enter Cost price',
    errorNumHours: 'Please Enter number of hours',
    existCostnameErrorMsg:'Cost name already exists. Please enter a different name'
}

export const deleteProduct = {
    popupTitle: 'Delete product?',
    costPopupTitle: 'Delete cost?',
    deleteDescription: 'This product will be deleted permanently from your quote.',
    deleteButton: 'Delete',
    costDeleteDescription: 'This cost will be deleted permanently from your quote.',
    deleteQuoteTitle:'Delete quote?',
    deleteQuoteMessage:'This quote will be deleted permanently including all of the job details.',
    filePopupTitle: 'Delete item?',
    deleteFileMessage: 'This item will be deleted permanently from your quote'
}

export const changeAccount = {
    popupTitle: 'Change Account',
    changeAccDescription: 'Changing your account now will remove all your items in the cart.  Please confirm you want to change account',
    cancel: 'Cancel',
    change: 'Change'
}

export const viewQuote = {
    clientName: 'Name:',
    phone: 'Phone:',
    email: 'Email:',
    address: 'Address:',
    dateIssued: 'Date issued:',
    scopeOfWork: 'SCOPE OF WORK',
    materialsLabel: 'MATERIALS & PRODUCTS',
    numberOfProducts: 'NO. OF PRODUCTS',
    priceLabel: 'PRICE',
    allMaterialsLabel: 'All Materials',
    costHeading: 'LABOUR / OTHER COSTS',
    allCostsLabel: 'All Costs',
    subtotal: 'Sub total',
    gst: 'GST',
    total: 'All Costs',
    termsAndConditionsLabel: 'TERMS AND CONDITIONS',
    paymentTermsLabel: 'PAYMENT TERMS',
    companyDetailsLabel: 'COMPANY DETAILS',
    companyDetailsContent: 'Include your company details, logo, terms & conditions, Payments  terms to display on the quote',
    editDetailsBtn: 'Edit Details',
    rrpLabel:'RRP',
    rrpInfoLabel:"Price only includes TradeLink's products",
    displayOptionTitle:'CLIENT DISPLAY OPTIONS',
    materialTitle:'Materials & Products',
    retailPriceLabel:'Show Retail Price',
    sectionBreakdownLabel:'Show section breakdown',
    costsTitle:'Costs',
    costBreakdownLabel:'Show Cost Breakdown',
    attachmentTitle:'Attachments',
    includeImagesLabel:'Include Images',
    includeFilesTitle:'Include files',
    jobDetailBtn:'Go to Job Details',
    include:'Include',
    includePopupMsg:'with quote',
    selectTxt:"Please select",
    addToQuoteTxt:'in  Job Details to add to your quote.',
    displayOptionsError:'Tools down, something went wrong. Please try again.',
    includePhotosFilesLabel:'Photos & Files',
    totalPrice:'Total',
    goBack : 'Go back',
    sendToCustomer: 'Send to Customer',
    labourCost : 'Total Labour Costs',
    otherCost : 'Total Other Costs'
}

export const companyProfile = {
    companysetUp:'Company Setup',
    infoText:'Details entered here will be displayed on the quote provided to your customer.',
    subInfo:'You will only have to enter this once but you can make changes at any time.',
    companyName:'Company name',
    companyLogo:'Company logo',
    fileUploadErr:"Logo's can be JPEG or PNG files only, and no larger than 500KB.",
    phNumber:'Phone no',
    address:'Customer Address',
    email:'Email Address',
    termsAndCondition:'Terms and conditions',
    paymentTerms:'Payment terms',
    saveDetails:'Save Details',
    companyAddressPlaceholder:'Enter your company address',
    removeLogo:'Remove logo',
    removeLogoInfo:'Are you sure you want to remove your company logo?'

}
export const sendToQuote = {
    sendQuote:'Send Quote',
    PDFbeingGeneratedTxt:'PDF is being generated...',
    successMsg:'is ready to send!',
    failureMsg:'There was an error generating your quote PDF. Please ensure you have updated your company details and try again',
    to:'To',
    cc:'CC',
    subjectLine:'Subject line', 
    yourMsg:'Your message',
    send:'Send',
    niceJob:'Nice Job!',
    successMsgInfo:'We’ve sent a copy of the quote to your email address so you have a record of it',
    successMsgSubInfo:'Now that you have finished your quote you can find it in the Pending section where you can make changes and mark it as Accepted or Declined once you’ve heard back from your customer.',
    returnToQuotePage:'Return To Customer Quotes',
    tryAgain:'Please try again.'
}
export const stageOfBuild = {
    buildStage:'Build stage',
    deleteStage:'Delete stage?',
    addStageBuild:'Add a stage of build',
    stageOfInfo:'Create the stages for the job and then add your materials',
    popupTitle: 'Delete ',
    popupTitleStage:' stage?',
    deleteMessage:'All products in this stage will be deleted permanently from your quote',
    addAnotherStage:'Add another stage',
    duplicateNameErrorMsg:'Stage of build name already exists against this quote. Please enter a new one.',
    stageDeletedMessage:'was removed from your quote'
}




