export const ELEMENT_DATA = [
  {
    Format_Title: 'AroFlo Price File',
    Format: 'csv',
    Format_type: 'Price',
    Attributes: {
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_description': 'Custom text',
      'ProductDept.name': 'Custom text',
      'ProductGroup.name': 'Custom text',
      'ProductSubGroup.name': 'Custom text',
      'Constant Custom text Barcodes': 'Custom text',
      'Constant Custom text Calculated Cost': 'Custom text',
      'Constant Custom text Calculated Cost Type': 'Custom text',
      'Constant Custom text Identifier': 'Custom text',
      'Constant Custom text IsSoR': 'Custom text',
      'Constant Custom text Quantity': 'Custom text',
      'Constant Custom text Manufacturer': 'Custom text',
      'Constant Custom text Markup': 'Custom text',
      'Constant Custom text Sell Type': 'Custom text',
      'Constant Custom text Unit Of Measure': 'Custom text',
      'Constant Custom text Unit Type': 'Custom text'
    },
  },
  {
    Format_Title: 'CavSoft Price File',
    Format: 'dat',
    Format_type: 'Price',
    Attributes: {
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_department': 'Custom text',
      'Product.jde_description': 'Custom text',
      'Product.jde_group': 'Custom text',
      'Product.jde_sub_group': 'Custom text',
      'Product.jde_uom_primary': 'Custom text',
    },
  },
  {
    Format_Title: 'CavSoft Price File',
    Format: 'dta',
    Format_type: 'Price',
    Attributes: {
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_department': 'Custom text',
      'Product.jde_description': 'Custom text',
      'Product.jde_group': 'Custom text',
      'Product.jde_sub_group': 'Custom text',
      'Product.jde_uom_primary': 'Custom text',
    },
  },
  {
    Format_Title: 'CavSoft Price File',
    Format: 'txt',
    Format_type: 'Price',
    Attributes: {
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_department': 'Custom text',
      'Product.jde_description': 'Custom text',
      'Product.jde_group': 'Custom text',
      'Product.jde_sub_group': 'Custom text',
      'Product.jde_uom_primary': 'Custom text',
    },
  },
  {
    Format_Title: 'Default Price File',
    Format: 'csv',
    Format_type: 'Price',
    Attributes: {
      '#currentdatetime#': 'Custom text',
      '#GST#': 'Custom text',
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_department': '',
      'Product.jde_description': '',
      'Product.jde_group': '',
      'Product.jde_sub_group': '',
      'Product.jde_uom_primary': '',
      'ProductDept.name': '',
      'ProductGroup.name': '',
      'ProductSubGroup.name': ''
    },
  },
  {
    Format_Title: 'Default Invoice',
    Format: 'csv',
    Format_type: 'Invoice',
    Attributes: {
      'CustomerHeaderRecord.document_type': 'Custom text',
      'CustomerHeaderRecordBillTo.draft_number': 'Custom text',
      'description': 'Custom text',
      'gst_value': 'Custom text',
      'Invoice.customer_number': 'Custom text',
      'Invoice.customer_order_ref': 'Custom text',
      'Invoice.gst_total': 'Custom text',
      'Invoice.invoice_date': 'Custom text',
      'Invoice.invoice_number': 'Custom text',
      'Invoice.invoice_total_ex_gst': 'Custom text',
      'Invoice.invoice_total_inc_gst': 'Custom text',
      'Invoice.sales_order_number': 'Custom text',
      'list_price': 'Custom text',
      'orig_invoice_number': 'Custom text',
      'product_code': 'Custom text',
      'quantity': 'Custom text',
      'ReturnAddress.business_name': 'Custom text',
      'shipment_number': 'Custom text',
      'unit_of_measure': 'Custom text',
      'unit_price_exc_gst': 'Custom text',
      'value_exc_gst': 'Custom text',
    },
  },
  {
    Format_Title: 'Fergus Price File',
    Format: 'csv',
    Format_type: 'Price',
    Attributes: {
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_description': 'Custom text',
    },
  },
  {
    Format_Title: 'MYOB Cloud Price File',
    Format: 'txt',
    Format_type: 'Price',
    Attributes: {
      '#GST#': 'Custom text',
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_description': 'Custom text',
      'Product.jde_uom_primary': 'Custom text',
    },
  },
  {
    Format_Title: 'SmartTrade Invoice',
    Format: 'csv',
    Format_type: 'Invoice',
    Attributes: {
      'product_code': 'Custom text',
      'description': 'Custom text',
      'Invoice.invoice_number': 'Custom text',
      'Invoice.invoice_date': 'Custom text',
      'unit_of_measure': 'Custom text',
      'quantity': 'Custom text',
      'list_price': 'Custom text',
      'total_net_price_ex_gst': 'Custom text',
      'gst_value': 'Custom text',
      'total_price_inc_gst': 'Custom text',
    },
 },
  {
    Format_Title: 'simPRO Price File',
    Format: 'csv',
    Format_type: 'Price',
    Attributes: {
      '#currentdatetime#': 'Custom text',
      '#GST#': 'Custom text',
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_department': 'Custom text',
      'Product.jde_description': 'Custom text',
      'Product.jde_group': 'Custom text',
      'Product.jde_sub_group': 'Custom text',
      'Product.jde_uom_primary': 'Custom text',
      'ProductDept.name': 'Custom text',
      'ProductGroup.name': 'Custom text',
      'ProductSubGroup.name': 'Custom text',
    },
  },
  {
    Format_Title: 'simPRO Price File',
    Format: 'txt',
    Format_type: 'Price',
    Attributes: {
      '#currentdatetime#': 'Custom text',
      '#GST#': 'Custom text',
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_department': 'Custom text',
      'Product.jde_description': 'Custom text',
      'Product.jde_group': 'Custom text',
      'Product.jde_sub_group': 'Custom text',
      'Product.jde_uom_primary': 'Custom text',
      'ProductDept.name': 'Custom text',
      'ProductGroup.name': 'Custom text',
      'ProductSubGroup.name': 'Custom text',
    },
  },
  {
    Format_Title: 'simPRO Invoice',
    Format: 'csv',
    Format_type: 'Invoice',
    Attributes: {
      'HDR': 'Custom text',
      'SI': 'Custom text',
      'Id': 'Custom text',
      'docNumber': 'Custom text',
      'docDate': 'Custom text',
      'customerPOReference': 'Custom text',
      'orderId': 'Custom text',
      'totalEx': 'Custom text',
      'totalGSTValue': 'Custom text',
      'totalInc': 'Custom text',
      'ITM': 'Custom text',
      'sku': 'Custom text',
      'Description': 'Custom text',
      'shipmentRef': 'Custom text',
      'stringValue': 'Custom text',
      'unitOfMeasure': 'Custom text',
      'quantityOrdered': 'Custom text',
      'sellPrice': 'Custom text',
      'tax': 'Custom text',
      'subtotal': 'Custom text',
    },
  },
  {
    Format_Title: 'XERO AU Price File',
    Format: 'csv',
    Format_type: 'Price',
    Attributes: {
      '#GST#': 'Custom text',
      'CustomerPriceItem.buy_price': 'Custom text',
      'CustomerPriceItem.jde_item_no': 'Custom text',
      'CustomerPriceItem.sell_price': 'Custom text',
      'Product.jde_description': 'Custom text',
    },
  },
];
